[package]
name = "dbrain-population"
version.workspace = true
edition.workspace = true

[dependencies]
deadlock-brain-core = { path = "../deadlock-brain-core" }
anyhow = { workspace = true }
clap = { workspace = true }
reqwest = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
sqlx = { workspace = true }
tokio = { workspace = true }

[dev-dependencies]
