\set ON_ERROR_STOP on
SELECT 'CREATE ROLE brain_migrate LOGIN'
WHERE NOT EXISTS (SELECT FROM pg_roles WHERE rolname = 'brain_migrate') \gexec
SELECT 'CREATE ROLE brain_ingest LOGIN'
WHERE NOT EXISTS (SELECT FROM pg_roles WHERE rolname = 'brain_ingest') \gexec
SELECT 'CREATE ROLE brain_service LOGIN'
WHERE NOT EXISTS (SELECT FROM pg_roles WHERE rolname = 'brain_service') \gexec
SELECT 'CREATE ROLE brain_readonly LOGIN'
WHERE NOT EXISTS (SELECT FROM pg_roles WHERE rolname = 'brain_readonly') \gexec

ALTER ROLE brain_migrate  NOSUPERUSER NOCREATEDB NOCREATEROLE NOREPLICATION NOBYPASSRLS NOINHERIT CONNECTION LIMIT 3;
ALTER ROLE brain_ingest   NOSUPERUSER NOCREATEDB NOCREATEROLE NOREPLICATION NOBYPASSRLS NOINHERIT CONNECTION LIMIT 4;
ALTER ROLE brain_service  NOSUPERUSER NOCREATEDB NOCREATEROLE NOREPLICATION NOBYPASSRLS NOINHERIT CONNECTION LIMIT 16;
ALTER ROLE brain_readonly NOSUPERUSER NOCREATEDB NOCREATEROLE NOREPLICATION NOBYPASSRLS NOINHERIT CONNECTION LIMIT 2;
ALTER ROLE brain_readonly SET default_transaction_read_only = on;

SELECT 'CREATE DATABASE brain OWNER brain_migrate ENCODING ''UTF8'' TEMPLATE template0'
WHERE NOT EXISTS (SELECT FROM pg_database WHERE datname = 'brain') \gexec
ALTER DATABASE brain OWNER TO brain_migrate;
REVOKE ALL ON DATABASE brain FROM PUBLIC;
REVOKE ALL ON DATABASE postgres FROM PUBLIC;
REVOKE ALL ON DATABASE template1 FROM PUBLIC;
GRANT CONNECT ON DATABASE brain TO brain_ingest, brain_service, brain_readonly;

\connect brain
REVOKE ALL ON SCHEMA public FROM PUBLIC;
ALTER SCHEMA public OWNER TO brain_migrate;
CREATE SCHEMA IF NOT EXISTS brain AUTHORIZATION brain_migrate;
ALTER SCHEMA brain OWNER TO brain_migrate;
REVOKE ALL ON SCHEMA brain FROM PUBLIC;
