[package]
name = "dbrain-session-store"
version.workspace = true
edition.workspace = true

[dependencies]
anyhow.workspace = true
postgres.workspace = true
serde_json.workspace = true
zeroize = "1"
serde.workspace = true
tokio.workspace = true
dl-token-secrets = { path = "../../../../Deadlock-Bots/rust/crates/dl-token-secrets" }
tb-crypto = { path = "../../../../Deadlock-Twitch-Bot/rust/crates/tb-crypto" }
